### ISSUE TITLE
[Feature-Request] Additional Information Regarding the Repositories Suggested

### ISSUE THREAD

**Issue by RamolaWeb** [csurfer/gitsuggest#16]
Since the information about the suggested repositories does not contains the information regarding the **Language of the Project** , **Star** and  **Fork** , It will be great to add these information while suggesting the repositories to the user. This will not only help to choose the best repositories for them based on their Language and fork but also provide ease for the user to start working on the project provided.

**Comment by marius92mc** [comment]
With the exception of **Fork**, the other labels are already appearing at listing [suggestions](https://gitsuggest.herokuapp.com/).

**Comment by csurfer** [comment]
@marius92mc : The command line still doesn't. Hence have kept it open.

**Comment by csurfer** [comment]
@RamolaWeb, @marius92mc : Now the UI of http://www.gitsuggest.com and of the command line generated temp html file both are the same. So you do get extra information like the language of the project and stars on the project. Haven't included forks for the moment.
