### ISSUE TITLE
please implement SOME kind of caching

### ISSUE THREAD

**Issue by kootenpv** [csurfer/gitsuggest#17]
we do not care about **complete** results as much... just give us **some** suggestions.

I had to try 4 times and still no results, now through all rate limits.

- old version (0.0.3), crashed
- without password, didn't finish
- first logged in, missing nltk stopwords
- second

       enchant.errors.DictNotFoundError: Dictionary for language 'en_US' could not be found

- third, rate limited

If you would have stored the information and deleted it after a successful interpretation, this wouldn't have had to happen. Maybe implement storing results to `/tmp`?

**Comment by csurfer** [comment]
@kootenpv: There needs to be some caching but I am torn between the idea of cached results and showing stale results. You are absolutely right that showing stale results is better than not showing anything at all. Let me try on a middle ground and implement the same. 

Anyways, 0.0.3 was showing all results it could and was not using paging effectively. The more I realised that people hardly look past 50th result I implemented paging which reduces the number of requests made drastically. 

So, for now, I would suggest using the latest pypi version which is 0.0.8 which is much better than 0.0.3 until I implement caching with the middle ground.

**Comment by csurfer** [comment]
@kootenpv : Checkout the repo in the current state. A lot of paging and reuse of created objects has been included to make it fast. Let me know if this is still a concern else we can close this out.

**Comment by kootenpv** [comment]
Thanks, I'm having suggestions now :)

**Comment by csurfer** [comment]
@kootenpv: Also check out http://www.gitsuggest.com to use it as a web service.
