### ISSUE TITLE
2FA issue

### ISSUE THREAD

**Issue by aleksandar-todorovic** [csurfer/gitsuggest#4]
As you might imagine, getting the password from a user won't really work if the user has 2FA set up and authenticates to GitHub via SSH.

    $ gitsuggest aleksandar-todorovic
    Password: 
    Generating suggestions...
    Traceback (most recent call last):
      File "/usr/local/bin/gitsuggest", line 11, in <module>
        load_entry_point('gitsuggest==0.0.3', 'console_scripts', 'gitsuggest')()
      File "/usr/local/lib/python2.7/dist-packages/gitsuggest/commandline.py", line 56, in main
        gs = GitSuggest(arguments.username, password)
      File "/usr/local/lib/python2.7/dist-packages/gitsuggest/suggest.py", line 53, in __init__
        raise ValueError('Unable to authenticate the user.')

**Comment by alex-gable** [comment]
For 2FA, [Github recommends](https://developer.github.com/v3/auth/#working-with-two-factor-authentication) using OAuth tokens via the Authorizations API. [Example here](https://gist.github.com/thruflo/e3fbd47fbb7ee3c626bb) and [documentation here](https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization).

**Comment by a86c6f7964** [comment]
also you can create a token in the UI here https://github.com/settings/tokens
