### ISSUE TITLE
Use public API and rate-limit appropriately

### ISSUE THREAD

**Issue by kasbah** [csurfer/gitsuggest#5]
Thanks for the tool and your response on Reddit. I would still prefer not to type my password into the script and instead just have it rate-limit its requests to fit the unauthenticated quota. #4 could be avoided as well.

**Comment by Qix-** [comment]
Yep. Would love to try this, but refuse to type my password into anything (regardless of if it uses it or not, it's just not a habit I want to get into).

**Comment by csurfer** [comment]
The script in total makes ~5 users/repo fetch and 3 search API calls. I currently have no way to make it more appropriate. The recent version does allow to press enter without keying in anything for the password i,e skip the password. In which case it assumes you have chosen to go the unauthenticated route which might have a lower rate limit. More info here:  https://github.com/csurfer/gitsuggest#faq

Using it without password i,e just pressing enter when asked for the password without keying in your password should work for you guys at the moment. With respect to making the rate limited calls more economically, I am all ears if you have any suggestions to make.

**Comment by kasbah** [comment]
I would suggest just waiting longer between requests if the user is unauthenticated.
