### ISSUE TITLE
py3 incompatibility 

### ISSUE THREAD

**Issue by imbolc** [csurfer/gitsuggest#6]
After `pip install` in default py3 environment it runs with appropriate error. Would you add some restrictions to setup.py?

**Comment by bryant1410** [comment]
and at least advise it in the readme

**Comment by csurfer** [comment]
Currently testing if the py3 bugs that exists in gensim can be worked around, if I couldn't will remove support for py3 altogether. Sadly travis.ci doesn't work well with pyenchant to ensure such bugs are kept out.

**Comment by bryant1410** [comment]
> Currently testing if the py3 bugs that exists in gensim can be worked around, if I couldn't will remove support for py3 altogether. Sadly travis.ci doesn't work well with pyenchant to ensure such bugs are kept out.

what py3 bugs exist in gensim?

**Comment by csurfer** [comment]
@bryant1410 : Using py3 with the same code I am running into error 'RuntimeWarning: invalid value encountered in double_scalars'

**Comment by bryant1410** [comment]
But gensim declares to support Python 3 and I have used with it. Can you provide the whole stacktrace?

**Comment by csurfer** [comment]
@bryant1410 : It was a bug due to erroneous filtering which was throwing the above error and giving an empty page. Now its fixed. Please update to latest version and you should have no problems.
